version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: blogdb
    ports:
      - "3306:3306"
    networks:
      - blog-network

  blog-app:
    build: .
    container_name: blog-backend-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/blogdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yourpassword
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
